# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CollapsibleTableVIew' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CollapsibleTableVIew
     pod 'CollapsibleTableSectionViewController' 
  target 'CollapsibleTableVIewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CollapsibleTableVIewUITests' do
    # Pods for testing
  end

end
